Document: bgrep
Title: Debian bgrep Manual
Author: <insert document author here>
Abstract: This manual describes what bgrep is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bgrep/bgrep.sgml.gz

Format: postscript
Files: /usr/share/doc/bgrep/bgrep.ps.gz

Format: text
Files: /usr/share/doc/bgrep/bgrep.text.gz

Format: HTML
Index: /usr/share/doc/bgrep/html/index.html
Files: /usr/share/doc/bgrep/html/*.html
